name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests py${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install via Makefile
        run: |
          make setup

      - name: Lint
        run: |
          make lint

      - name: Unit tests
        run: |
          # Skip slow tests in CI. They can run locally or in a manual workflow.
          make test

      - name: Build sdist and wheel
        run: |
          python -m pip install build twine
          python -m build
          python -m twine check dist/*



